# Generated by Django 4.2.16 on 2024-09-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=80)),
                ('year_founded', models.IntegerField(default=0)),
                ('industry', models.IntegerField(default=0)),
                ('size_range', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=80)),
                ('linkedin_url', models.CharField(max_length=150)),
                ('current_employee_estimate', models.IntegerField(default=0)),
                ('total_employee_estimate', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'csv_data',
            },
        ),
    ]
