# Generated by Django 4.2.16 on 2024-09-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_app', '0002_alter_csvmodel_industry_alter_csvmodel_year_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='current_employee_estimate',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='total_employee_estimate',
            field=models.CharField(max_length=80),
        ),
    ]
